### ISSUE TITLE
hash check false positive

### ISSUE THREAD

**Issue by marcvfr** [Te-k/phpscanner#4]
Hello,
thanks for this great tool.

I hav a problem with hash checking in WP fresh installation. A lot of files are marked [HASH] whereas they seem OK.

Do you know why ? How to be sure HASH check is working ?
Thanks

./phpscanner.py -v -v -v /home/test/www/
/home/test/www/wp-comments-post.php -> [HASH]
/home/test/www/wp-load.php -> [HASH]
/home/test/www/xmlrpc.php -> [HASH]
/home/test/www/wp-mail.php -> [HASH]
..

**Comment by Te-k** [comment]
Hi Marc,
The hash detection is not 100% perfect as any modification done by you on these files would lead to a false positive. 
But if it is a fresh install, it may be detected only because I have not included the last Wordpress version in the database. Can you tell me which version you are using?

**Comment by marcvfr** [comment]
Wp version is 4.6.1.
Thanks

**Comment by Te-k** [comment]
I just updated the database with the last Wordpress versions, it should be ok now

**Comment by Te-k** [comment]
I close the issue, feel free to reopen it needed
