### ISSUE TITLE
I am teh malware?

### ISSUE THREAD

**Issue by wireghoul** [Te-k/phpscanner#7]
Your Yara rule matching my nick over the actual directives/functions that makes htshells work is a pretty poor rule.

You end up letting anyone using one of the many copycat .htaccess shells sail right through and false positive flag my other work...

Just an idea...

Cheers

**Comment by Te-k** [comment]
It is not mine, but created for https://github.com/nbs-system/php-malware-finder. At the same time, if your pseudonym end up regularly in webshells, I think it is a pretty good one. 

Anyway, this project is not maintained anymore, I close
